apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ray-metrics
  namespace: kube-prometheus-stack
  labels:
    app: ray
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      ray.io/node-type: head
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    targetPort: 8080
  namespaceSelector:
    matchNames:
    - default
---
apiVersion: v1
kind: Service
metadata:
  name: ray-head-metrics
  namespace: default
  labels:
    ray.io/node-type: head
    app: ray
spec:
  selector:
    ray.io/node-type: head
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
