---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: cnn-training-queue
  namespace: default
spec:
  weight: 1
  capability:
    cpu: '500'
    memory: 1500Gi

---


apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: kuberay-gpu
  namespace: default
  labels:
    ray.io/scheduler-name: volcano
    volcano.sh/queue-name: cnn-training-queue
spec:
  rayVersion: 2.22.0
  headGroupSpec:
    rayStartParams:
      dashboard-host: 0.0.0.0
    template:
      spec:
        containers:
        - name: ray-head
          image: ${ECR_URL}
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
          ports:
          - containerPort: 8265
            name: dashboard
            protocol: TCP
          - containerPort: 6379
            name: redis
            protocol: TCP
          - containerPort: 10001
            name: object-manager
            protocol: TCP
          resources:
            requests:
              cpu: 2
              memory: 8Gi
          volumeMounts:
          # - mountPath: /tmp/ray
          #   name: log-volume
          # - mountPath: /shared
          #   name: persistent-storage
          - mountPath: /data
            name: jfs-dataset
        nodeSelector:
          workload: rayhead
        volumes:
        # - name: log-volume
        #   emptyDir: {}
        # - name: persistent-storage
        #   persistentVolumeClaim:
        #     claimName: fsx-claim
        - name: jfs-dataset
          persistentVolumeClaim:
            claimName: jfs-dataset
  workerGroupSpecs:
  - groupName: workergroup
    replicas: 2
    minReplicas: 2
    maxReplicas: 2
    numOfHosts: 1
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker
          image: ${ECR_URL}
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
          ports:
          - containerPort: 8265
            name: dashboard
            protocol: TCP
          - containerPort: 6379
            name: redis
            protocol: TCP
          - containerPort: 10001
            name: object-manager
            protocol: TCP
          resources:
            limits:
              cpu: "6"
              memory: 24Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "6"
              memory: 24Gi
              nvidia.com/gpu: "1"
          volumeMounts:
          # - mountPath: /shared
          #   name: persistent-storage
          # - mountPath: /dev/shm
          #   name: dshm
          # - mountPath: /tmp/ray
          #   name: log-volume
          - mountPath: /data
            name: jfs-dataset
        nodeSelector:
          instance-type: g6-2xl
          provisioner: cluster-autoscaler
        tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
        - effect: NoSchedule
          key: hub.jupyter.org/dedicated
          operator: Equal
          value: user
        volumes:
        # - name: persistent-storage
        #   persistentVolumeClaim:
        #     claimName: fsx-claim
        # - name: dshm
        #   emptyDir:
        #     medium: Memory
        # - name: log-volume
        #   emptyDir: {}
        - name: jfs-dataset
          persistentVolumeClaim:
            claimName: jfs-dataset
