apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob1
  namespace: default
spec:
  submissionMode: K8sJobMode
  entrypoint: "cd /cnn_training && python3 ray_ddp.py"
  runtimeEnvYAML: |
    working_dir: /cnn_training
    env_vars:
      PYTHONUNBUFFERED: '0'
      TF_VAR_ray_cluster_result_s3bucket_url: '${RAY_CLUSTER_RESULT_S3BUCKET_URL}'
    pod_spec:
      containers:
      - name: ray-worker
        volumeMounts:
        - mountPath: /data
          name: jfs-dataset
      volumes:
      - name: jfs-dataset
        persistentVolumeClaim:
          claimName: jfs-dataset
  clusterSelector:
    ray.io/cluster: kuberay-gpu
    rayClusterNamespace: default  # Replace with the namespace where your RayCluster is deployed
  shutdownAfterJobFinishes: true
  ttlSecondsAfterFinished: 60  # Time to live for the pod after completion (in seconds)
