apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: test
  namespace: default
spec:
  submissionMode: K8sJobMode
  entrypoint: "cd /cnn_training && python3 ray_ddp.py"
  runtimeEnvYAML: |
    working_dir: /cnn_training
    env_vars:
      PYTHONUNBUFFERED: '0'
  clusterSelector:
    ray.io/cluster: kuberay-gpu
    rayClusterNamespace: default  # Replace with the namespace where your RayCluster is deployed
  shutdownAfterJobFinishes: true
  ttlSecondsAfterFinished: 60  # Time to live for the pod after completion (in seconds)