apiVersion: v1
kind: Pod
metadata:
  name: data-load-pod
spec:
  containers:
  - name: app
    image: python:3.9
    command: ["/bin/bash", "-c"]
    args:
      - |
        pip install --upgrade pip && \
        pip install torch==2.1.1+cpu torchvision==0.16.1+cpu torchaudio==2.1.1+cpu --index-url https://download.pytorch.org/whl/cpu --trusted-host download.pytorch.org && \
        pip install filelock && \
        cd /data && \
        python -c "
        import os
        from filelock import FileLock
        from torchvision import datasets, transforms
        from torchvision.transforms import Normalize, ToTensor

        transform = transforms.Compose([ToTensor(), Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

        with FileLock('/data/data.lock'):
            training_data = datasets.CIFAR10(
                root='/data/',
                train=True,
                download=True,
                transform=transform,
            )
            testing_data = datasets.CIFAR10(
                root='/data/',
                train=False,
                download=True,
                transform=transform,
            )
        print('CIFAR10 dataset downloaded successfully to /data')
        " && \
        sleep infinity
    volumeMounts:
    - name: jfs-data
      mountPath: /data
      readOnly: false
  volumes:
  - name: jfs-data
    persistentVolumeClaim:
      claimName: jfs-dataset

